# fly.toml app configuration file generated for mercadona-pro on 2023-12-01T22:08:17+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mercadona-pro"
primary_region = "cdg"

[build]

[env]
  PHX_HOST = "mercadona-pro-empty.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
